# Generated by Django 3.2 on 2021-09-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='tumorimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tphoto', models.ImageField(upload_to='tumorimage')),
            ],
        ),
    ]
