# Generated by Django 3.2 on 2021-09-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tumorimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tumorimage',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
