# Generated by Django 3.2 on 2021-09-11 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_remove_tumorimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tumorimage',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tumorimage',
            name='tphoto',
            field=models.ImageField(blank=True, upload_to='tumorimage'),
        ),
    ]
