# Generated by Django 3.2 on 2021-09-11 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_tumorimage_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='cameraimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tphoto', models.FileField(blank=True, upload_to='tumorcamra')),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
