# Generated by Django 3.2 on 2021-09-11 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cameraimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tumorimage',
        ),
    ]
